fix(phase-0.7.9): correct alembic x_args to use cmd_opts.x
The -x arguments are stored in config.cmd_opts.x (a list of 'key=value'
strings), not config.x_args which doesn't exist. This fixes the
KeyError: 'url' in async_engine_from_config().